version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./extracted:/app/extracted
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
